### ISSUE TITLE
Generate code from json schema?

### ISSUE THREAD

**Issue by bwasty** [alteous/gltf#19]
Hi,
Have you considered generating the Rust code from the official json schema?
I did a quick experiment with `schemafiy`, but immediately ran into Marwes/schemafy#3 (panic on external references).

I got the idea initially from https://github.com/slack-rs/slack-rs-api/tree/master/codegen. They use a custom generator to generate bindings to the Slack API. It works pretty well there (I've worked with the generated code).

Side question: How far along is the 2.0 branch?

**Comment by alteous** [comment]
> Have you considered generating the Rust code

Yes. The idea of generating code like [`gl`](https://github.com/brendanzab/gl-rs) or `slack-rs` as you mentioned is tempting. I decided against it originally because there seemed to be too many special cases. For example when items require 'non-standard' defaults, when extensions are introduced into the mix, and what to do with extras.

I think it is more reasonable for `gl` to generate code rather than `gltf` because the former is generating function prototypes which are much simpler than hierarchical data structures. Having said this though, I'm not against the idea. It would just requires a lot more thought.

The glTF 2.0 implementation is in the [`incoming`](https://github.com/alteous/gltf/tree/incoming) branch and is 'almost complete'. I'm waiting for the specification to be finalised before the code is merged into `master` and uploaded to crates.io.

**Comment by bwasty** [comment]
Thanks for the answer. I also had the feeling it might be a little more complex than `slack-rs`.
I'm thinking of writing a glTF viewer with [`​gfx-rs/gfx`](https://github.com/gfx-rs/gfx) (as a 'small' exercise to get back into graphics programming). I think I'll base it on the `incoming` branch if I get there before it's merged.

**Comment by alteous** [comment]
> as a 'small' exercise to get back into graphics programming

To save you time I encourage you to [read this](https://github.com/alteous/gltf/pull/10#issuecomment-289281839) and take my mistakes into consideration (TL;DR: don't use `gfx`). Recently I've been experimenting with a new graphics API, namely [`rugl`](https://github.com/gregtatum/rugl) which is much reasonable for this use case.

**Comment by bwasty** [comment]
Hmm, difficult choice. What I like about `gfx` is that it supports Vulkan and OpenGL ES (-> can possibly be compiled to WebAssembly(gfx-rs/gfx#641)).

**Comment by alteous** [comment]
I should add what I said above only applies to glTF 1.0. It would be very reasonable to use gfx for glTF 2.0.

**Comment by alteous** [comment]
Random thought: It might be worth using the schema to validate the correctness of the hand written 'raw' data structures.

**Comment by bwasty** [comment]
How would you do that?

Btw, the glTF-Sample-Models repo now contains a few more models updated to 2.0 and e.g. `Box` can't be loaded with the v2 loader. Also failing is the minimal example here: https://github.com/javagl/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_003_MinimalGltfFile.md
Both work with https://gltf-viewer.donmccurdy.com/

**Comment by alteous** [comment]
Thanks for reporting. I've updated the sample models in `incoming`. Hopefully a fix will be released soon.

**Comment by alteous** [comment]
Recently I've been experimenting with generating Rust code from the current 2.0 schema. 

I think writing a code generator would be too troublesome at this stage due to the complexity of the schema. Even if there exists a smart person that could write it all up tonight, whatever code is generated is unlikely to be correct tomorrow, and worse still would probably fail silently.

**Comment by bwasty** [comment]
>The glTF 2.0 implementation is in the incoming branch and is 'almost complete'. I'm waiting for the specification to be finalised before the code is merged into master and uploaded to crates.io.

https://www.khronos.org/news/press/khronos-releases-gltf-2.0-specification 😃

**Comment by bwasty** [comment]
Another thing: I noticed one relevant recent spec change under [Scenes](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#scenes):

>When scene is undefined, runtime is not required to render anything at load time.

>> Implementation Note: This allows applications to use glTF assets as libraries of individual entities such as materials or meshes.

So [this](https://github.com/alteous/gltf/blob/incoming/src/v2/root.rs#L97) _could_ be removed I guess.

**Comment by alteous** [comment]
> So this could be removed I guess.

I think it's important to provide all the data from the glTF. Whether the user decides to make use of the default scene index is up to them.

**Comment by bwasty** [comment]
Well, the part of the spec saying that the default scene (if not specified) is 0 was removed, so the default should now be `None` I think.

**Comment by alteous** [comment]
Thanks, I've made the change.

Whatever 2.0-specific code is in the incoming branch should be ready for a `0.5.0` release. I'll check it over again and publish in a few hours.
