### ISSUE TITLE
Reason for Source trait to use &mut self instead of &self?

### ISSUE THREAD

**Issue by fst3a** [alteous/gltf#31]
https://github.com/alteous/gltf/blob/wrapper/src/import.rs#L79

Is there a reason to have &mut self instead of &self?  Logically, we are not changing the Source when reading from it.  If implementer would need it to be mutable, they could use RefCell, Mutex or else *inside* of their implementation.  This would make user code working with functions that take Source cleaner as the locks in non-concurrent Sources would be hidden inside the implementation instead of being propagated to the user code.

**Comment by alteous** [comment]
> Is there a reason to have &mut self instead of &self?

There is no compelling reason other than giving the user the opportunity to mutate their `Source` implementation. As you quite rightly say, the user could use a `RefCell`, `Mutex`, or otherwise instead. I agree the code would be cleaner with `&self`.

I've been experimenting with the `Source` trait lately. Here is the latest iteration:

```rust
/// A trait for representing sources of glTF data that may be read by an importer.
pub trait Source: std::fmt::Debug {
    /// Error type.
    type Err: std::error::Error + std::fmt::Debug;
    
    /// Read the contents of a .gltf or .glb file.
    fn gltf(&mut self) -> Result<Box<Read>, Self::Err>;
    
    /// Read the contents of a glTF buffer.
    fn buffer(&mut self, &json::buffer::Buffer) -> Result<Box<Read>, Self::Err>;

    /// Read the contents of a glTF image.
    fn image(&mut self, &json::image::Image) -> Result<Box<Read>, Self::Err>;
}

/// Error encountered when importing a glTF 2.0 asset.
#[derive(Debug)]
pub enum Error<S: Source> {
    /// Failure when deserializing a .gltf metadata file.
    Deserialize(serde_json::error::Error),
    
    /// A glTF extension required by the asset has not been enabled by the user.
    ExtensionDisabled(String),
    
    /// A glTF extension required by the asset is not supported by the library.
    ExtensionUnsupported(String),
    
    /// The glTF version of the asset is incompatible with the importer.
    IncompatibleVersion(String),

    /// I/O error.
    Io(std::io::Error),
    
    /// Data source error.
    Source(S::Err),

    /// The .gltf data is invalid.
    Validation(Vec<validation::Error>),
}
```

The reference implementation takes `&self`:

```rust
    impl Source for FromPath {
        type Err = std::io::Error;

        fn gltf(&self) -> Result<Vec<u8>, Self::Err> {
            let file = File::open(path)?;
            Ok(Box::new(BufReader::new(file)))
        }

        fn buffer(&self, buffer: &json::buffer::Buffer) -> Result<Vec<u8>, Self::Err> {
            let uri = unwrap_uri(&buffer.uri)?;
            let path = self.path.parent().unwrap_or(Path::new("./")).join(uri);
            let file = File::open(path)?;
            Ok(Box::new(BufReader::new(file)))
        }

        fn image(&self, image: &json::image::Image) -> Result<Box<Read>, Self::Err> {
            let uri = unwrap_uri(&image.uri)?;
            let path = self.path.parent().unwrap_or(Path::new("./")).join(uri);
            Ok(Box::new(BufReader::new(file)))
        }
    }
```

**Comment by fst3a** [comment]
I see.  So in 1.0 it's going to be &self?

**Comment by alteous** [comment]
Maybe. There isn't too much harm using `&mut self` since [we take `source`](https://github.com/alteous/gltf/blob/wrapper/src/import.rs#L159) in the importer. It's a question of whether we should allow side-effects during the import process. I don't think it's a good idea, for example, allowing the user to change the behaviour of a `Source` between calls to `gltf`, `buffer`, and `image`. Having `&mut self` means the user can perform other inconsequential side effects, like opening and storing a `TcpStream`.

**Comment by alteous** [comment]
Closed since the `Source` trait has been redesigned and no longer takes `&mut self`.
